Origin/feature/header mob menu
yulyaolshanska/project_group_10 pull request #12
Opened 2022-01-28 15:49 UTC by Max-Loktionov

2022-01-28 16:19 UTC, Annka-Sarviro commented on src/sass/components/_header.scss
> +  padding-right: 20px;
Паддинги на общем классе контейнера Юля прописала

2022-01-28 16:33 UTC, yulyaolshanska requested changes

2022-01-28 16:33 UTC, yulyaolshanska commented on src/sass/components/_header.scss
> +  --mobile-menu-bgc: #e17992;
Это нужно добавить в файл _variables

2022-01-28 16:33 UTC, yulyaolshanska commented on src/sass/components/_header.scss
> +.button {
Стили для кнопок не нужно дублировать.

2022-01-28 16:33 UTC, yulyaolshanska commented on src/sass/components/_header.scss
> +  font-family: DM Sans;
86стр font-family можешь не писать, он в body

2022-01-28 16:33 UTC, yulyaolshanska commented on src/sass/components/_header.scss
> +.site-nav__link {
81стр Не пойму зачем эти падинги.

2022-01-28 16:33 UTC, yulyaolshanska commented on src/partials/header.html
> +      icecream
Это можно в span

2022-01-28 16:33 UTC, yulyaolshanska commented on src/partials/header.html
> +    <button type="button" class="mobile-menu__button">
Не нашла класс mobile-menu

2022-01-28 16:33 UTC, yulyaolshanska commented on src/partials/header.html
> +        <a href="#" class="site-nav__link current">Home </a>
48 стр site-nav__link--current вместо site-nav__link current

2022-01-28 17:06 UTC, SerhiiDubovets approved these changes

2022-01-28 17:06 UTC, SerhiiDubovets commented on src/partials/header.html
> +        alt="Мороженое рожок"
скорее всего на английском нужно)

2022-01-28 17:06 UTC, SerhiiDubovets commented on src/partials/header.html
> +  <div class="header__container">
Этот контейнер отличается от общего?

2022-01-28 18:37 UTC, yulyaolshanska commented on src/partials/header.html
> +        alt="Мороженое рожок"
Да, alt на английском

2022-01-28 21:14 UTC, Max-Loktionov commented on src/sass/components/_header.scss
> +  padding-right: 20px;
Согласен

2022-01-28 21:15 UTC, Max-Loktionov commented on src/sass/components/_header.scss
> +  --mobile-menu-bgc: #e17992;
Не согласен, для чего каждый оттенок, который встречается 1 или 2 раза писать в var

2022-01-28 21:16 UTC, Max-Loktionov commented on src/sass/components/_header.scss
> +.button {
Исправлю

2022-01-28 21:17 UTC, yulyaolshanska commented on src/sass/components/_header.scss
> +  --mobile-menu-bgc: #e17992;
Ну ты же сам сделал его, просто добавь в другой файл.

2022-01-28 21:21 UTC, Max-Loktionov commented on src/partials/header.html
> +        <a href="#" class="site-nav__link current">Home </a>
Скорее всего это вообще не current

2022-01-28 21:22 UTC, Max-Loktionov commented on src/partials/header.html
> +  <div class="header__container">
Отличается, паддинги уберутся, а он будет внутри секции и container hero

2022-01-29 06:29 UTC, Max-Loktionov commented on src/sass/components/_header.scss
> +  padding-right: 20px;
Убрал

2022-01-29 06:30 UTC, Max-Loktionov commented on src/sass/components/_header.scss
> +  --mobile-menu-bgc: #e17992;
Упс... в общем исправлено, добавлено в var - не мной

2022-01-29 06:45 UTC, Max-Loktionov commented on src/sass/components/_header.scss
> +.button {
+

2022-01-29 06:47 UTC, Max-Loktionov commented on src/sass/components/_header.scss
> +  font-family: DM Sans;
убрал

2022-01-29 06:47 UTC, Max-Loktionov commented on src/sass/components/_header.scss
> +.site-nav__link {
убрал

2022-01-29 08:05 UTC, Max-Loktionov commented on src/partials/header.html
> +      icecream
сделал

2022-01-29 08:05 UTC, Max-Loktionov commented on src/partials/header.html
> +    <button type="button" class="mobile-menu__button">
появилось

2022-01-29 08:11 UTC, Max-Loktionov commented on src/partials/header.html
> +        <a href="#" class="site-nav__link current">Home </a>
исправил, но нужна помощь в определении состояния-положения-класса этой ссылки

2022-01-29 08:13 UTC, Max-Loktionov commented on src/partials/header.html
> +        alt="Мороженое рожок"
yes, sir

2022-01-29 11:53 UTC, yulyaolshanska approved these changes

2022-01-29 11:53 UTC, merged