Footer
yulyaolshanska/project_group_10 pull request #15
Opened 2022-01-28 16:33 UTC by SerhiiDubovets

Нужны правки

2022-01-28 17:16 UTC, Annka-Sarviro commented on src/sass/components/_footer.scss
> +p {
эти стили есть в базовых стилях

2022-01-28 17:23 UTC, Annka-Sarviro commented on src/sass/components/_footer.scss
> +  font-family: DM Sans;
Font-family есть на body

2022-01-28 17:24 UTC, Annka-Sarviro commented on src/sass/components/_footer.scss
> +  &::after {
Тут нормально, просто интересно, почему не бефором?)

2022-01-28 17:25 UTC, Annka-Sarviro commented on src/sass/components/_footer.scss
> +  font-family: DM Sans;
Font-family есть на body

2022-01-28 17:26 UTC, Annka-Sarviro commented on src/partials/example.html
> +<!-- <article class="example">
Нужно спросить у Юли, вроде эти файлы уже не нужны, можно удалять

2022-01-28 17:26 UTC, Annka-Sarviro commented on src/sass/_example.scss
> +// .example {
эту тестовую вроде тоже можно удалить

2022-01-28 17:27 UTC, Annka-Sarviro commented on src/sass/components/_footer.scss
> +  @media screen and (max-width: 767px) {
max-width: 767px - есть в переменных

2022-01-28 17:31 UTC, Annka-Sarviro commented on src/partials/footer.html
> +  <div class="container footer_container">
Давайте придерживаться одного стиля при названии. Footer__container и т.д.

2022-01-28 17:33 UTC, Annka-Sarviro commented on src/sass/components/_footer.scss
> +.container_title {
такие стили есть в section__title, в базовых стилях

2022-01-28 19:18 UTC, yulyaolshanska requested changes

2022-01-28 19:18 UTC, yulyaolshanska commented on src/images/symbol-defs.svg
> +</svg>\
37 стр </svg>\ Затесался лишний символ

2022-01-28 19:18 UTC, yulyaolshanska commented on src/sass/components/_footer.scss
> +  background-color: #fff5f6;
47стр background-color: #fff5f6; задать переменной

2022-01-28 19:18 UTC, yulyaolshanska commented on src/sass/components/_footer.scss
> +.container_text {
63 стр Это общий класс section__label, задавать стили не нужно, они в файле common. Задавай только отступы и то, что отличается от общих.

2022-01-28 19:18 UTC, yulyaolshanska commented on src/sass/components/_footer.scss
> +.container_title {
90стр Это общий класс section__title, задавать стили не нужно, они в файле common. Задавай только отступы и то, что отличается от общих.

2022-01-28 19:18 UTC, yulyaolshanska commented on src/sass/components/_footer.scss
> +  margin-bottom: 43px;
91 стр Нижний отступ задай footer_title-block. Иначе title пробивает родительский блок.

2022-01-28 19:18 UTC, yulyaolshanska commented on src/partials/footer.html
> +      <ul class="footer_item">
8 стр ul - list, li-item

2022-01-28 19:18 UTC, yulyaolshanska commented on src/partials/footer.html
> +    <div class="footer_social-block">
7cтр Лучше сделать блок social, а дальше его элементы social__list, social__svg

2022-01-28 19:18 UTC, yulyaolshanska commented on src/sass/components/_footer.scss
> +  color: #d41443;
Все цвета сделать переменными, все есть в файле _variables

2022-01-28 19:18 UTC, yulyaolshanska commented on src/sass/components/_footer.scss
> +  margin-bottom: 65px;
149 стр margin-bottom: 65px; Задать блоку .adress иначе пробивает родителя.

2022-01-28 19:18 UTC, yulyaolshanska commented on src/sass/components/_footer.scss
> +  line-height: 186%;
155стр line-height: 186%; задавать не в процентах, нужно 1.8

2022-01-28 19:18 UTC, yulyaolshanska commented on src/sass/components/_footer.scss
> +    line-height: 186%;
168стр line-height: 186%; не в процентах

2022-01-29 11:32 UTC, Max-Loktionov approved these changes

2022-01-29 11:32 UTC, Max-Loktionov commented on src/sass/components/_footer.scss
> +.container_title {
67,68 скорее всего можно удалить
70, 86, 79в относительных единицах

2022-01-29 11:32 UTC, Max-Loktionov commented on src/sass/components/_footer.scss
> +  line-height: 186%;
152 точно нужна? font-style:normal 
153 здесь не задаётся численно? font-weight

2022-01-29 12:25 UTC, yulyaolshanska approved these changes

2022-01-29 12:25 UTC, merged