Feature/advantages
yulyaolshanska/project_group_10 pull request #24
Opened 2022-01-28 23:05 UTC by ElenaBelaya

паддинги и маржины выровняю, когда будут общие параметры. в следующий раз доделаю иконки.

2022-01-28 23:25 UTC, Annka-Sarviro commented on src/sass/components/_advantages.scss
> +  margin-top: 38px;
обнулить верхний марджин у первой li

2022-01-28 23:26 UTC, Annka-Sarviro commented on src/partials/advantages.html
> +<section class="section">
Добавить background на секцию

2022-01-28 23:28 UTC, Annka-Sarviro commented on src/sass/components/_advantages.scss
> +    display: flex;
правильно сделать разметку сетки флекс (отрицательные марджины и т.д.)

2022-01-28 23:29 UTC, Annka-Sarviro commented on src/sass/components/_advantages.scss
> +  display: block;
одинаковые картинки на псевдоэлементе

2022-01-28 23:34 UTC, Annka-Sarviro commented on src/sass/components/_advantages.scss
> +  margin-top: 38px;
а для других разрешений экрана нужно убдрать все верхние марджины, ну или там делать флекс-контейнер с отрицательными и т.д.

2022-01-28 23:36 UTC, Annka-Sarviro commented on src/sass/components/_advantages.scss
> +  font-size: 12px;
как  мне кажется, необходимо как-то сделать, чтоб текст переносился на другую строку, а не в одну. Но я не уверена сдась, может еще кто подскажет

2022-01-29 08:49 UTC, Annka-Sarviro requested changes

2022-01-29 08:49 UTC, Annka-Sarviro commented on src/sass/components/_advantages.scss
> +  }
Ничего не значащий комментария

2022-01-29 13:20 UTC, yulyaolshanska requested changes

2022-01-29 13:20 UTC, yulyaolshanska commented on src/partials/advantages.html
> +        <ul class="advantages__list">
Есть класс advantages__list, но неn просто класса advantages.
 container__advantages можно сделать блоком advantages

2022-01-29 13:20 UTC, yulyaolshanska commented on src/sass/components/_advantages.scss
> +  font-size: 12px;
Нужно задать max-width: ; для  .advantages__text (он везде разный)

2022-01-29 15:00 UTC, ElenaBelaya commented on src/sass/components/_advantages.scss
> +  font-size: 12px;
сначала я хочу залить общие параметры контейнера, в потом "поиграться" с текстом.

2022-01-29 15:11 UTC, ElenaBelaya commented on src/partials/advantages.html
> +        <ul class="advantages__list">
исправлено

2022-01-29 15:13 UTC, ElenaBelaya commented on src/sass/components/_advantages.scss
> +  margin-top: 38px;
верхние марджины хочу откорректирова, когда залью общие свойства контейнера

2022-01-29 15:29 UTC, ElenaBelaya commented on src/partials/advantages.html
> +        <ul class="advantages__list">
если вместо контейнера задать класс advantages, то тогда надо делать еще одну обертку container, чтобы свойства контейнера применились?

2022-01-29 15:34 UTC, yulyaolshanska commented on src/sass/components/_advantages.scss
> +  margin-top: 38px;
Ты их можешь залить сейчас, они уже есть.

2022-01-29 15:34 UTC, yulyaolshanska commented on src/sass/components/_advantages.scss
> +  font-size: 12px;
Ты их можешь залить сейчас, они уже есть.

2022-01-29 15:35 UTC, yulyaolshanska commented on src/partials/advantages.html
> +        <ul class="advantages__list">
Можно advantages сделать третим классом

2022-01-29 19:11 UTC, yulyaolshanska approved these changes

2022-01-29 19:11 UTC, merged