ee
yulyaolshanska/project_group_10 pull request #31
Opened 2022-01-29 14:50 UTC by SlavikKlimov1988

eee

2022-01-29 16:32 UTC, SerhiiDubovets requested changes

2022-01-29 16:32 UTC, SerhiiDubovets commented on src/partials/hero.html
> +<section class="hero sectoin">
Не верно класс section

2022-01-29 16:32 UTC, SerhiiDubovets commented on src/partials/hero.html
> +      <span class="hero___titel--white"
может title и в3 строчке

2022-01-29 16:32 UTC, SerhiiDubovets commented on src/partials/hero.html
> +      src="./images/Hero/hero-icecream-mobile.png"
А не так?  ../ и так далее во всем коде

2022-01-29 16:32 UTC, SerhiiDubovets commented on src/sass/_common.scss
> +    width: 1080px;
может 1280

2022-01-29 16:32 UTC, SerhiiDubovets commented on src/sass/components/_hero.scss
> +}
Если не нужно можно удалить медиа

2022-01-29 16:32 UTC, SerhiiDubovets commented on src/sass/components/_hero.scss
> +  color: #d41443;
цвет в переменных есть

2022-01-29 16:32 UTC, SerhiiDubovets commented on src/sass/components/_hero.scss
> +  border: 1px solid #d41443;
цвет в переменных

2022-01-29 16:32 UTC, SerhiiDubovets commented on src/sass/components/_hero.scss
> +  background-color: #d41443;
цвет в переменных

2022-01-29 16:32 UTC, SerhiiDubovets commented on src/sass/components/_hero.scss
> +    font-family: DM Sans;
На body задано

2022-01-29 16:32 UTC, SerhiiDubovets commented on src/sass/components/_hero.scss
> +    font-family: DM Sans;
общий стиль

2022-01-29 17:45 UTC, yulyaolshanska requested changes

2022-01-29 17:45 UTC, yulyaolshanska commented on src/partials/hero.html
> +<section class="hero sectoin">
Все имена картинок с маленькой буквы.  Ellipse-white.png неправильно

2022-01-29 17:45 UTC, yulyaolshanska commented on src/partials/hero.html
> +<section class="hero sectoin">
1cтр попутал буквы sectoin

2022-01-29 17:45 UTC, yulyaolshanska commented on src/sass/_common.scss
>  .container {
Стили для common не нужно подтягивать. Залей обновленный dev в свою ветку.

2022-01-29 18:11 UTC, Annka-Sarviro commented on src/sass/components/_hero.scss
> +  padding-left: 20px;
Этот паддинг должен быть на контейнере(в базовых стилях он есть)

2022-01-29 18:11 UTC, Annka-Sarviro commented on src/sass/components/_hero.scss
> +  display: flex;
Насколько здесь нужен flex? блоки и так бы вертикально стали б

2022-01-29 18:14 UTC, Annka-Sarviro commented on src/sass/components/_hero.scss
> +  margin-right: 10px;
Обнулить правый марджин у крайнего элемента

2022-01-29 18:18 UTC, Annka-Sarviro commented on src/partials/hero.html
> +      <a href="#"></a>
Что это за ссылка?

2022-01-29 18:19 UTC, Annka-Sarviro commented on src/partials/hero.html
> +      <a href="#"></a>
на макете потерялась кнопочка со стрелочкой, эта ссылка ее должна быть?

2022-01-29 18:20 UTC, Annka-Sarviro commented on src/partials/hero.html
> +      src="./images/Hero/hero-icecream-mobile.png"
Адаптивные картинки загружаются через picture, а так получается грузятся все

2022-01-29 18:23 UTC, Annka-Sarviro commented on src/partials/hero.html
> +    <img class="hero__tasty" src="/images/Hero/hero-girl-tablet.png" alt="" />
ДОбавить адаптивные картинки и заполнить alt

2022-01-29 18:26 UTC, yulyaolshanska requested changes

2022-01-29 18:26 UTC, yulyaolshanska commented on src/partials/hero.html
> +      <span class="hero___titel--white"
3cтр есть общий класс section__title, его добавить к hero__titel

2022-01-29 18:26 UTC, yulyaolshanska commented on src/partials/hero.html
> +      <span class="hero___titel--white"
3cтр есть общий класс section__title, его добавить к hero__titel

2022-01-29 18:26 UTC, yulyaolshanska commented on src/sass/components/_hero.scss
> +    background-image: url(/images/Hero/Ellipse-tab.png);
12стр Неправильный путь к картинке, нужно ../images/Hero/Ellipse-mob.png

2022-01-29 18:26 UTC, yulyaolshanska commented on src/sass/components/_hero.scss
> +    background-image: url(/images/Hero/Ellipse.png);
Неправильный путь

2022-01-29 18:26 UTC, yulyaolshanska commented on src/partials/hero.html
> +      class="hero__ice-cream"
Картинки через <picture>

2022-01-29 18:26 UTC, yulyaolshanska commented on src/partials/hero.html
> +      class="hero__ice-cream"
Картинки через <picture

2022-01-29 18:50 UTC, yulyaolshanska requested changes

2022-01-29 18:50 UTC, yulyaolshanska commented on src/sass/components/_hero.scss
> +    margin-left: -418px;
118 стр .hero__icon-milk должна позиционироваться абсолютно, а не  margin-left: -418px; ( ТЗ "Картинки на герое спозиционировать абсолютно.")

2022-01-29 18:50 UTC, yulyaolshanska commented on src/sass/components/_hero.scss
> +    font-style: normal;
152-153  font-style: normal; font-weight: normal; не нужно писать.

2022-01-29 18:50 UTC, yulyaolshanska commented on src/sass/components/_hero.scss
> +    line-height: 32px;
line-height не в px, а 1.14

2022-01-29 18:50 UTC, yulyaolshanska commented on src/sass/components/_hero.scss
> +    line-height: 10px;
168стр line-height не в px, а 1.25

2022-01-29 18:50 UTC, yulyaolshanska commented on src/sass/components/_hero.scss
> +    margin-bottom: 14px;
143стр .hero__item {
  @media screen and (min-width: $tablet) {
    margin-bottom: 14px;    
    сделать через :not(:LAST-CHILD)

2022-01-30 10:22 UTC, SlavikKlimov1988 commented on src/partials/hero.html
> +      src="./images/Hero/hero-icecream-mobile.png"
по другому выкидывает на другой уровень

2022-01-30 10:22 UTC, SlavikKlimov1988 commented on src/sass/components/_hero.scss
> +}
это поправится держу для простоты пока не закончил код до конца

2022-01-30 10:23 UTC, SlavikKlimov1988 commented on src/sass/components/_hero.scss
> +  color: #d41443;
это опять таки версия демо в финале подставлю переменную

2022-01-30 10:24 UTC, SlavikKlimov1988 commented on src/sass/components/_hero.scss
> +    font-family: DM Sans;
знаю записал для себя опять таки это демка просто проверить рабоиу красоту в коде навожу потом когда уверен что все работает

2022-01-30 10:25 UTC, SlavikKlimov1988 commented on src/partials/hero.html
> +<section class="hero sectoin">
+ поправлю

2022-01-30 10:25 UTC, SlavikKlimov1988 commented on src/partials/hero.html
> +<section class="hero sectoin">
видел

2022-01-30 10:26 UTC, SlavikKlimov1988 commented on src/sass/components/_hero.scss
> +  margin-right: 10px;
+

2022-01-30 10:27 UTC, SlavikKlimov1988 commented on src/partials/hero.html
> +      <a href="#"></a>
да поскольку не понятно кнопка то или ссылка, стрелка может переводить кулато а может и открывать что то

2022-01-30 10:28 UTC, SlavikKlimov1988 commented on src/sass/components/_hero.scss
> +    background-image: url(/images/Hero/Ellipse-tab.png);
по другому не срабатывает не знаю почему

2022-01-30 10:29 UTC, SlavikKlimov1988 commented on src/sass/components/_hero.scss
> +    margin-left: -418px;
+

2022-01-30 10:29 UTC, SlavikKlimov1988 commented on src/sass/components/_hero.scss
> +    font-style: normal;
знаю демо версия

2022-01-30 10:29 UTC, SlavikKlimov1988 commented on src/sass/components/_hero.scss
> +    line-height: 32px;
спасибо поправлю

2022-01-30 10:30 UTC, SlavikKlimov1988 commented on src/sass/components/_hero.scss
> +    margin-bottom: 14px;
+

2022-01-30 17:23 UTC, yulyaolshanska approved these changes

2022-01-30 17:23 UTC, yulyaolshanska commented on src/partials/hero.html
> +      <img
Структура picture 
<picture>
          <source
            media="(min-width: 1280px)"
            srcset="
              ./images/About/about-cow-desktop.png    1x,
              ./images/About/about-cow-desktop@2x.png 2x
            "
          /
          <source
            media="(min-width: 768px)"
            srcset="
              ./images/About/about-cow-tablet.png    1x,
              ./images/About/about-cow-tablet@2x.png 2x
            "
          
          <source
            media="(min-width: 320px)"
            srcset="
              ./images/About/about-cow-mobile.png    1x,
              ./images/About/about-cow-mobile@2x.png 2x
            "
          
          <img
            src="./images/About/about-cow-tablet.png"
            class="about__img"
            alt="Cow with a jug of milk"
          
        </picture

2022-01-30 17:23 UTC, yulyaolshanska commented on src/partials/hero.html
> +      <img
У тебя нет <source
        media="(min-width: px)"

2022-01-30 17:37 UTC, merged